name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out repository code
        uses: actions/checkout@v4
      
      # Install Node.js (version 20)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install

      # Run linting
      - name: Run lint
        run: yarn lint

      # Start the application in the background
      - name: Start the application
        run: |
          yarn start &  
          sleep 10

      # Run tests
      - name: Run tests
        run: yarn test

      # Log in to docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # The root of the repository
          file: ./Dockerfile  # Specify the Dockerfile location (root)
          tags: mongskeu/webapp:latest  # Tagging the image
          push: true  # Do not push the image yet

        #niks